-- Mikono — 05: read-only access for the public demo
-- Creates a locked-down role + user so a Streamlit Community Cloud deployment
-- can READ the exchange and call Cortex, but cannot alter data or schema.
-- Run as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;
USE DATABASE MIKONO;
USE SCHEMA CORE;

-- A tiny warehouse the public app uses, capped so a runaway demo can't burn credits.
CREATE WAREHOUSE IF NOT EXISTS MIKONO_PUBLIC_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 30
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Resource monitor: hard stop if the public demo ever exceeds a small quota.
CREATE RESOURCE MONITOR IF NOT EXISTS MIKONO_PUBLIC_RM
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE MIKONO_PUBLIC_WH SET RESOURCE_MONITOR = MIKONO_PUBLIC_RM;

CREATE ROLE IF NOT EXISTS MIKONO_READONLY;

-- Read + Cortex, nothing else.
GRANT USAGE ON WAREHOUSE MIKONO_PUBLIC_WH TO ROLE MIKONO_READONLY;
GRANT USAGE ON DATABASE MIKONO TO ROLE MIKONO_READONLY;
GRANT USAGE ON SCHEMA MIKONO.CORE TO ROLE MIKONO_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA MIKONO.CORE TO ROLE MIKONO_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA MIKONO.CORE TO ROLE MIKONO_READONLY;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE MIKONO_READONLY;

-- A dedicated demo user. Set a password when you run this (replace the value).
CREATE USER IF NOT EXISTS MIKONO_DEMO
  DEFAULT_ROLE = MIKONO_READONLY
  DEFAULT_WAREHOUSE = MIKONO_PUBLIC_WH
  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE MIKONO_READONLY TO USER MIKONO_DEMO;

-- Then set the password once, out of band:
--   ALTER USER MIKONO_DEMO SET PASSWORD = '<a strong password>';
